### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/dream-team#38]
### Список багов

- [x] В слайдере нет infinity slide
- [x] Не работает drag&slide
- [x] Нету SVG Morph
- [x] Тут все еще actl
- [x] У сферы кривой background (https://github.com/torin-asakura/dream-team/issues/37)
- [x] Проверить что форма обратной связи в порядке

**Comment by TFK70** [comment]
@dakand есть небольшая проблема с анимацией [этих](https://www.figma.com/file/OFpidYSscy6NOYWpRsfdwt/DreamTeam-web-site?node-id=134%3A5356) иконок

Суть в том, что сейчас (https://dream-team.tech) на странице контактов у кнопок "копировать" нет никакой плавности при переходе между состояниями. Мы выделили 2 способа как это можно решить:

1. SVG Morph - плавно трансформировать первое состояние во второе ([примеры](https://css-tricks.com/svg-shape-morphing-works/))
2. Анимация stroke, чтобы был эффект рисования ([пример](https://betterprogramming.pub/how-to-easily-animate-svg-with-a-few-css-lines-77c999ea3aea))

Проблема в том, что текущие иконки плохо подходят под оба варианта. Первое состояние довольно трудно трансформировать во второе потому что там нету общих вершин, а если анимировать stroke, то получается что-то такое:


https://user-images.githubusercontent.com/62806448/176911021-c28c853b-acbb-478e-b98d-5969626fcbfc.mov

Это потому что иконка выглядит так, как она выглядит из-за свойства fill, при анимации stroke, fill очень сильно мешает, а анимировать его отдельно и синхронизировать анимации - тоже довольно трудно

Поэтому я предлагаю заменить вторую иконку, чтобы было что-то похожее:


https://user-images.githubusercontent.com/62806448/176911555-3de2f0fa-72fe-4684-a782-6c9f918991b6.mov

Но вместо крестика подразумевается галочка или что-то в этом роде

То есть основное требование к иконке которой мы анимируем stroke - отсутствие свойства fill

Как в целом смотришь на это и какую иконку мне в таком случае можно заюзать?

**Comment by dakand** [comment]
@TFK70 принял, сегодня сделаю

**Comment by TFK70** [comment]
@TorinAsakura 

###  Ошибка

[Актуальное состояние](https://github.com/torin-asakura/dream-team/pull/41)

При попытке [загрузить](https://github.com/torin-asakura/dream-team/blob/feat/sphere/ui/sphere/src/sphere.component.tsx#L10) `.mtl` файл выбрасывается ошибка. Проблема в том, что самой ошибки нигде нет, в логах есть только это:

<details>

```shell
The above error occurred in the <Sphere> component:

    at Sphere
    at LoadableImpl (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/shared/lib/loadable.js:101:38)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at LandingHero (webpack-internal:///../../../.yarn/__virtual__/@fragments-landing-hero-virtual-fd6c051adb/1/fragments/landing-hero/src/landing-hero.component.tsx:50:26)
    at Index (webpack-internal:///../../../.yarn/__virtual__/@landing-index-page-virtual-d7f41fcd5b/1/landing/index/src/index.component.tsx:34:83)
    at IndexPage
    at App (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/pages/_app.js:177:9)
    at WithHelmet (webpack-internal:///../../../.yarn/__virtual__/@atls-next-app-with-helmet-virtual-78f79fd2a1/0/cache/@atls-next-app-with-helmet-npm-0.2.65-cb707ded54-537b7c54dc.zip/node_modules/@atls/next-app-with-helmet/dist/with-helmet.provider.js:10:48)
    at ThemeProvider (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:101:21)
    at ThemeProvider (webpack-internal:///../../../.yarn/__virtual__/@ui-theme-virtual-3b228d920d/1/ui/theme/src/theme.provider.tsx:19:26)
    at WithEmotion (webpack-internal:///../../../providers/next-app-with-emotion/src/with-emotion.provider.tsx:142:17)
    at ApolloProvider (webpack-internal:///../../../.yarn/__virtual__/@apollo-client-virtual-806d022637/0/cache/@apollo-client-npm-3.3.21-b0c859aa0b-cdb501045c.zip/node_modules/@apollo/client/react/context/ApolloProvider.js:13:21)
    at Bare (webpack-internal:///./pages/_app.tsx:61:27)
    at ErrorBoundary (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/client/index.js:357:9)
    at AppContainer (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/client/index.js:791:26)
    at Root (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/client/index.js:915:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

</details>

И да, как я уже сказал - никакой "above error" нету, это единственный лог

**Как дебажил** - ставил логи на каждой строчке, таким образом я и выяснил что приложение падает на [этой](https://github.com/torin-asakura/dream-team/blob/feat/sphere/ui/sphere/src/sphere.component.tsx#L10) строке (ее же выше указывал)

Сначала можно подумать что проблема элементарно в том, что у меня не загружается ресурс, сам `.mtl` файл, но нет:

<details>

![image](https://user-images.githubusercontent.com/62806448/176730343-0cc4e660-47cf-4fbd-a37f-14379538cf3e.png)


</details>

На скрине выделен пакет с `.mtl` файлом

###  К слову

Ориентировался на [этот](https://codesandbox.io/s/objloader-51zks?file=/src/App.js) сендбокс, даже версии либ взял оттуда

Нашел его [здесь](https://github.com/atls/workflow/issues/88#issuecomment-1171447897)

### Воспроизведение

Не смог закоммитить `.obj` и `.mtl` файлы потому что `.obj` слишком большой (174МБ), а лимит гитхаба на один файл - 100МБ, так что прикладываю их ссылкой на ЯД

1. Нужно взять `.obj` и `.mtl` файлы [отсюда](https://disk.yandex.ru/d/pMCLroIVaxTqyQ) (оригиналы брал [тут](https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1074831847), в своих файлах поправил имена)
2. Положить файлы в `landing/app/src/public`
3. `docker-compose run yarn && docker-compose up landing`
4. http://localhost:3000/
5. Ждем пока не появится белый экран и ошибка в консоли

**Comment by dakand** [comment]
@TFK70 сделал, комменты оставил на нужных иконках.
