### ISSUE TITLE
Шарик

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/dream-team#52]
###  Ошибка

[Актуальное состояние](https://github.com/torin-asakura/dream-team/pull/41)

При попытке [загрузить](https://github.com/torin-asakura/dream-team/blob/feat/sphere/ui/sphere/src/sphere.component.tsx#L10) `.mtl` файл выбрасывается ошибка. Проблема в том, что лога об ошибке нигде нет, есть только это:

<details>

```shell
The above error occurred in the <Sphere> component:

    at Sphere
    at LoadableImpl (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/shared/lib/loadable.js:101:38)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at div
    at eval (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:62:23)
    at LandingHero (webpack-internal:///../../../.yarn/__virtual__/@fragments-landing-hero-virtual-fd6c051adb/1/fragments/landing-hero/src/landing-hero.component.tsx:50:26)
    at Index (webpack-internal:///../../../.yarn/__virtual__/@landing-index-page-virtual-d7f41fcd5b/1/landing/index/src/index.component.tsx:34:83)
    at IndexPage
    at App (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/pages/_app.js:177:9)
    at WithHelmet (webpack-internal:///../../../.yarn/__virtual__/@atls-next-app-with-helmet-virtual-78f79fd2a1/0/cache/@atls-next-app-with-helmet-npm-0.2.65-cb707ded54-537b7c54dc.zip/node_modules/@atls/next-app-with-helmet/dist/with-helmet.provider.js:10:48)
    at ThemeProvider (webpack-internal:///../../../.yarn/__virtual__/@emotion-react-virtual-bc4d25dcf4/0/cache/@emotion-react-npm-11.9.3-dcd9c32ac6-19bc7205e8.zip/node_modules/@emotion/react/dist/emotion-element-c8f04419.browser.cjs.js:101:21)
    at ThemeProvider (webpack-internal:///../../../.yarn/__virtual__/@ui-theme-virtual-3b228d920d/1/ui/theme/src/theme.provider.tsx:19:26)
    at WithEmotion (webpack-internal:///../../../providers/next-app-with-emotion/src/with-emotion.provider.tsx:142:17)
    at ApolloProvider (webpack-internal:///../../../.yarn/__virtual__/@apollo-client-virtual-806d022637/0/cache/@apollo-client-npm-3.3.21-b0c859aa0b-cdb501045c.zip/node_modules/@apollo/client/react/context/ApolloProvider.js:13:21)
    at Bare (webpack-internal:///./pages/_app.tsx:61:27)
    at ErrorBoundary (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/client/index.js:357:9)
    at AppContainer (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/client/index.js:791:26)
    at Root (webpack-internal:///../../../.yarn/__virtual__/next-virtual-378579c9e8/0/cache/next-npm-12.1.0-7f99f50e0f-36dbafd5e6.zip/node_modules/next/dist/client/index.js:915:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

</details>

И да, как я уже сказал - никакой "above error" нету, это единственный лог

### Как дебажил

Ставил логи на каждой строчке, таким образом я и выяснил что приложение падает на [этой](https://github.com/torin-asakura/dream-team/blob/feat/sphere/ui/sphere/src/sphere.component.tsx#L10) строке (ее же выше указывал)

Сначала можно подумать что проблема элементарно в том, что у меня не загружается ресурс, сам `.mtl` файл, но нет:

<details>

![image](https://user-images.githubusercontent.com/62806448/176730343-0cc4e660-47cf-4fbd-a37f-14379538cf3e.png)

</details>

На скрине выделен пакет с `.mtl` файлом

### Все изменения с комментариями

- [Модуль со сферой](https://github.com/torin-asakura/dream-team/blob/feat/sphere/ui/sphere/src/sphere.component.tsx)
- Импортируется [через next/dynamic](https://github.com/torin-asakura/dream-team/blob/feat/sphere/fragments/landing-hero/src/landing-hero.component.tsx#L13) чтобы избежать ошибки `ReactDOM does not support React.Suspense yet`
- [Маунтится](https://github.com/torin-asakura/dream-team/blob/feat/sphere/fragments/landing-hero/src/landing-hero.component.tsx#L31)
- `.obj` и `.mtl` файлы хранятся в [public](https://github.com/torin-asakura/dream-team/tree/feat/sphere/landing/app/src/public)

###  Референсы

Ориентировался на [этот](https://codesandbox.io/s/objloader-51zks?file=/src/App.js) сендбокс, даже версии либ взял оттуда

Нашел его [здесь](https://github.com/atls/workflow/issues/88#issuecomment-1171447897)

### Воспроизведение

1. `docker-compose run yarn && docker-compose up landing`
2. http://localhost:3000/
3. Ждем пока не появится белый экран и ошибка в консоли

Оригинальные ассеты [тут](https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1074831847)

**Comment by TorinAsakura** [comment]
https://github.com/pmndrs/react-three-fiber/blob/ee8e7856c299e335033a0867144e1238ef814073/packages/fiber/src/core/hooks.tsx#L91

неправильное использование хуков, чтобы использовать useLoader, нужно чтобы в родительском компоненте был Suspense
